---
- name: restart cpufrequtils
  systemd:
    name: cpufrequtils
    state: restarted
  ignore_errors: yes

- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes