---
- name: Install storage optimization tools
  apt:
    name:
      - util-linux
      - hdparm
      - smartmontools
      - lvm2
      - mdadm
      - nvme-cli
    state: present
  tags: [packages]

- name: Configure fstrim timer for SSD optimization
  systemd:
    name: fstrim.timer
    enabled: yes
    state: started
  tags: [ssd, trim]

- name: Configure mount options for optimal performance
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+)(ext4)(\s+[^\s]+)(\s+.*)$'
    replace: '\1\2\3,noatime,nodiratime\4'
    backup: yes
  tags: [mount, fstab]

- name: Configure storage device readahead
  lineinfile:
    path: /etc/udev/rules.d/60-storage-readahead.rules
    line: 'ACTION=="add|change", KERNEL=="{{ item.device }}", ATTR{bdi/read_ahead_kb}="{{ item.readahead }}"'
    create: yes
    mode: '0644'
  loop:
    - { device: "md*", readahead: "4096" }
    - { device: "nvme*", readahead: "512" }
    - { device: "sd*", readahead: "2048" }
  tags: [readahead, storage]

# I/O scheduler configuration moved to host_performance_tuning role to avoid duplication

- name: Create storage monitoring script
  template:
    src: storage-monitor.sh.j2
    dest: /usr/local/bin/storage-monitor.sh
    mode: '0755'
  tags: [monitoring]

- name: Create SMART monitoring script
  template:
    src: smart-monitor.sh.j2
    dest: /usr/local/bin/smart-monitor.sh
    mode: '0755'
  tags: [monitoring, smart]

- name: Schedule storage health checks
  cron:
    name: "Storage health monitoring"
    hour: "2"
    minute: "0"
    job: "/usr/local/bin/storage-monitor.sh"
    user: root
  tags: [monitoring, cron]

- name: Schedule SMART monitoring
  cron:
    name: "SMART disk monitoring"
    minute: "*/30"
    job: "/usr/local/bin/smart-monitor.sh"
    user: root
  tags: [monitoring, smart, cron]

- name: Configure tmpfs for temporary files
  lineinfile:
    path: /etc/fstab
    line: "tmpfs /tmp tmpfs defaults,noatime,nosuid,size=2G 0 0"
    create: yes
    backup: yes
  tags: [tmpfs, memory]

- name: Configure swappiness for host system
  sysctl:
    name: vm.swappiness
    value: "{{ host_optimization.swappiness | default(10) }}"
    state: present
    reload: yes
  ignore_errors: yes  # Parameter may not exist on all kernel versions
  tags: [swap, memory]

# GRUB configuration moved to host_performance_tuning role to avoid conflicts
# zswap configuration is now included in the main GRUB line

- name: Configure file system cache pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    state: present
    reload: yes
  ignore_errors: yes  # Parameter may not exist on all kernel versions
  tags: [cache, memory]

- name: Configure dirty page writeback for heavy BitTorrent I/O
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "vm.dirty_ratio", value: "5" }
    - { key: "vm.dirty_background_ratio", value: "2" }
    - { key: "vm.dirty_expire_centisecs", value: "1500" }
    - { key: "vm.dirty_writeback_centisecs", value: "250" }
  ignore_errors: yes  # Parameters may not exist on all kernel versions
  tags: [writeback, memory, bittorrent]

- name: Create storage cleanup script
  template:
    src: storage-cleanup.sh.j2
    dest: /usr/local/bin/storage-cleanup.sh
    mode: '0755'
  tags: [cleanup]

- name: Schedule weekly storage cleanup
  cron:
    name: "Weekly storage cleanup"
    weekday: "0"
    hour: "3"
    minute: "0"
    job: "/usr/local/bin/storage-cleanup.sh"
    user: root
  tags: [cleanup, cron]