---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_host: 127.0.0.1
      
  vars:
    # Host OS Configuration Only
    system_timezone: "Europe/Berlin"
    system_locale: "en_US.UTF-8"
    
    # Host Hardware Info
    host_specs:
      cpu_model: "Intel(R) Core(TM) i7-8700"
      cpu_cores: 6
      cpu_threads: 12
      total_memory_gb: 125
      
    # Host OS Optimization Settings
    host_optimization:
      cpu_governor: "performance"
      transparent_hugepages: "madvise"
      swappiness: 10
      enable_zswap: true
      dirty_ratio: 15
      dirty_background_ratio: 5
      
    # Host Storage Paths (for monitoring only)
    host_storage:
      root_partition: "/dev/md2"
      home_partition: "/dev/md3"
      virt_partition: "/dev/nvme0n1p1"
      usage_alert_threshold: 90
      
    # Host Network Interface
    host_network:
      primary_interface: "eno1"
      
    # System Services to Optimize
    system_services:
      disable_unnecessary: true
      optimize_systemd: true
      
    # Kernel Parameters for Host (optimized values applied via roles)
    kernel_params:
      - "vm.swappiness=5"
      - "vm.dirty_ratio=5"
      - "vm.dirty_background_ratio=2"
      - "vm.vfs_cache_pressure=200"
      - "kernel.sched_autogroup_enabled=0"
      
    # BitTorrent Traffic Optimization
    bittorrent_optimization:
      enable_optimizations: true
      connection_tracking_max: 1048576
      tcp_fin_timeout: 15
      port_range: "1024 65535"
      
    # Enhanced Monitoring
    monitoring:
      enable_bt_monitoring: true
      enable_smart_monitoring: true
      log_retention_days: 30