---
- name: Ensure /tmp directory has correct permissions for apt
  file:
    path: /tmp
    owner: root
    group: root
    mode: '1777'
    state: directory
  tags: [system, packages]

- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [packages]

- name: Install essential host optimization packages
  apt:
    name:
      - htop
      - iotop
      - sysstat
      - numactl
      - irqbalance
      - tuned
      - cpufrequtils
      - ncdu
      - tree
      - bc
    state: present
  tags: [packages]

- name: Configure CPU frequency scaling
  lineinfile:
    path: /etc/default/cpufrequtils
    line: 'GOVERNOR="{{ host_optimization.cpu_governor | default("performance") }}"'
    create: yes
    mode: '0644'
  notify: restart cpufrequtils
  tags: [cpu]

- name: Configure transparent huge pages
  lineinfile:
    path: /etc/rc.local
    line: 'echo {{ host_optimization.transparent_hugepages | default("madvise") }} > /sys/kernel/mm/transparent_hugepage/enabled'
    create: yes
    mode: '0755'
  tags: [memory]

- name: Enable and start irqbalance
  systemd:
    name: irqbalance
    enabled: yes
    state: started
  tags: [irq]

- name: Configure tuned for virtual-host profile
  systemd:
    name: tuned
    enabled: yes
    state: started
  tags: [tuned]

- name: Check current tuned profile
  command: tuned-adm active
  register: tuned_current_profile
  changed_when: false
  tags: [tuned]

- name: Set tuned profile for virtualization host
  command: tuned-adm profile virtual-host
  when: "'Current active profile: virtual-host' not in tuned_current_profile.stdout"
  tags: [tuned]

- name: Disable unnecessary services for host optimization
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - bluetooth
    - cups
    - avahi-daemon
    - ModemManager
    - collector
  ignore_errors: yes
  when: system_services.disable_unnecessary | default(true)
  tags: [services]

- name: Remove SumoCollector installation
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/SumoCollector
    - /etc/systemd/system/collector.service
  ignore_errors: yes
  tags: [services, cleanup]

- name: Configure logrotate for system logs
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/host-optimization
    mode: '0644'
  tags: [logging]

- name: Configure systemd journal limits
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - { key: "SystemMaxUse", value: "500M" }
    - { key: "SystemMaxFileSize", value: "50M" }
    - { key: "MaxRetentionSec", value: "1week" }
  notify: restart systemd-journald
  tags: [logging]

- name: Create host optimization monitoring script
  template:
    src: host-monitor.sh.j2
    dest: /usr/local/bin/host-monitor.sh
    mode: '0755'
  tags: [monitoring]

- name: Schedule host monitoring cron job
  cron:
    name: "Host system monitoring"
    minute: "*/5"
    job: "/usr/local/bin/host-monitor.sh"
    user: root
  tags: [monitoring]


- name: Create BitTorrent traffic monitoring script
  template:
    src: bt-traffic-monitor.sh.j2
    dest: /usr/local/bin/bt-traffic-monitor.sh
    mode: '0755'
  tags: [monitoring, bittorrent]

- name: Schedule BitTorrent traffic monitoring
  cron:
    name: "BitTorrent traffic monitoring"
    minute: "*/5"
    job: "/usr/local/bin/bt-traffic-monitor.sh"
    user: root
  tags: [monitoring, bittorrent, cron]