---
- name: Install required packages for network management
  apt:
    name:
      - iptables-persistent
      - netfilter-persistent
      - bridge-utils
      - ethtool
    state: present
  tags: [network, packages]

- name: Create network configuration directory
  file:
    path: /etc/network/host-optimization
    state: directory
    mode: '0755'
  tags: [network, config]

- name: Create consolidated firewall rules script
  template:
    src: firewall-rules.sh.j2
    dest: /etc/network/host-optimization/firewall-rules.sh
    mode: '0755'
  notify: apply firewall rules
  tags: [network, firewall]

- name: Create NAT configuration script
  template:
    src: nat-config.sh.j2
    dest: /etc/network/host-optimization/nat-config.sh
    mode: '0755'
  notify: apply nat config
  tags: [network, nat]

- name: Create network tuning script
  template:
    src: network-tuning.sh.j2
    dest: /etc/network/host-optimization/network-tuning.sh
    mode: '0755'
  notify: apply network tuning
  tags: [network, tuning]

- name: Create comprehensive network setup script
  template:
    src: network-setup.sh.j2
    dest: /etc/network/host-optimization/network-setup.sh
    mode: '0755'
  tags: [network, setup]

- name: Create network setup systemd service
  template:
    src: network-setup.service.j2
    dest: /etc/systemd/system/network-setup.service
    mode: '0644'
  notify: 
    - reload systemd
    - enable network setup
  tags: [network, systemd]

- name: Create network interface configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces.d/host-optimization
    mode: '0644'
    backup: yes
  tags: [network, interfaces]

- name: Enable IP forwarding persistently
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  tags: [network, forwarding]

- name: Configure netfilter for bridge traffic
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
    - { key: "net.bridge.bridge-nf-call-arptables", value: "1" }
  ignore_errors: yes  # Bridge module may not be loaded
  tags: [network, bridge]

# Removed old network script cleanup from /root directory

- name: Create network monitoring script
  template:
    src: network-monitor.sh.j2
    dest: /usr/local/bin/network-monitor.sh
    mode: '0755'
  tags: [network, monitoring]

- name: Schedule network monitoring
  cron:
    name: "Network monitoring"
    minute: "*/10"
    job: "/usr/local/bin/network-monitor.sh"
    user: root
  tags: [network, monitoring]

- name: Save current iptables rules
  shell: |
    iptables-save > /etc/iptables/rules.v4
    ip6tables-save > /etc/iptables/rules.v6
  tags: [network, persistence]

- name: Enable netfilter-persistent service
  systemd:
    name: netfilter-persistent
    enabled: yes
    state: started
  tags: [network, services]

- name: Optimize network for BitTorrent traffic patterns
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "net.ipv4.ip_local_port_range", value: "1024 65535" }
    - { key: "net.ipv4.tcp_fin_timeout", value: "15" }
    - { key: "net.ipv4.tcp_tw_reuse", value: "1" }
    - { key: "net.core.somaxconn", value: "65535" }
    - { key: "net.ipv4.tcp_max_syn_backlog", value: "65535" }
    - { key: "net.ipv4.tcp_max_tw_buckets", value: "1440000" }
    - { key: "net.ipv4.tcp_timestamps", value: "1" }
    - { key: "net.ipv4.tcp_window_scaling", value: "1" }
    - { key: "net.ipv4.tcp_sack", value: "1" }
  tags: [network, bittorrent, performance]

- name: Optimize network interface for high traffic
  command: "{{ item }}"
  loop:
    - "ethtool -G {{ network_interfaces.primary }} rx 4096 tx 4096"
    # Disable checksumming to fix Intel I219-LM Hardware Unit Hangs
    - "ethtool -K {{ network_interfaces.primary }} tx off rx off"
    # Disable all offloading features to prevent Hardware Unit Hangs
    - "ethtool -K {{ network_interfaces.primary }} gso off gro off tso off sg off"
    - "ethtool -K {{ network_interfaces.primary }} rxvlan off txvlan off"
    # Flow control can remain enabled
    - "ethtool -A {{ network_interfaces.primary }} rx on tx on"
  ignore_errors: yes
  tags: [network, interface, performance]

- name: Create disable NIC offloading service
  template:
    src: disable-nic-offloading.service.j2
    dest: /etc/systemd/system/disable-nic-offloading.service
    mode: '0644'
  tags: [network, service, i219lm-fix]

- name: Enable and start disable NIC offloading service
  systemd:
    name: disable-nic-offloading
    enabled: yes
    state: started
    daemon_reload: yes
  tags: [network, service, i219lm-fix]