---
- name: Apply kernel parameters for host optimization
  sysctl:
    name: "{{ item.split('=')[0] }}"
    value: "{{ item.split('=')[1] }}"
    state: present
    reload: yes
  loop: "{{ kernel_params }}"
  ignore_errors: yes  # Some parameters may not exist on all kernel versions
  tags: [kernel, sysctl]

- name: Configure additional performance kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "net.core.rmem_max", value: "16777216" }
    - { key: "net.core.wmem_max", value: "16777216" }
    - { key: "net.ipv4.tcp_rmem", value: "4096 87380 16777216" }
    - { key: "net.ipv4.tcp_wmem", value: "4096 65536 16777216" }
    - { key: "net.core.netdev_max_backlog", value: "5000" }
    - { key: "vm.min_free_kbytes", value: "65536" }
    - { key: "vm.zone_reclaim_mode", value: "0" }
  ignore_errors: yes  # Some parameters may not exist on all kernel versions
  tags: [kernel, network, memory]

- name: Configure I/O scheduler for different storage devices
  lineinfile:
    path: /etc/udev/rules.d/60-io-scheduler.rules
    line: 'ACTION=="add|change", KERNEL=="{{ item.device }}", ATTR{queue/scheduler}="{{ item.scheduler }}"'
    create: yes
    mode: '0644'
  loop:
    - { device: "md*", scheduler: "deadline" }
    - { device: "nvme*", scheduler: "none" }
    - { device: "sd*", scheduler: "mq-deadline" }
  tags: [io, storage]

- name: Configure CPU, disable side-channel mitigations, and enable zswap for single-user system
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="quiet splash intel_pstate=disable processor.max_cstate=1 intel_idle.max_cstate=0 mitigations=off spectre_v2=off spec_store_bypass_disable=off l1tf=off mds=off tsx_async_abort=off zswap.enabled=1 zswap.compressor=lz4"'
    backup: yes
  notify: update grub
  tags: [cpu, grub, security, swap]

- name: Configure huge pages for host system
  lineinfile:
    path: /etc/sysctl.d/99-hugepages.conf
    line: "{{ item }}"
    create: yes
    mode: '0644'
  loop:
    - "vm.nr_hugepages = 1024"
    - "vm.hugetlb_shm_group = 0"
  notify: apply sysctl
  tags: [memory, hugepages]

- name: Configure network interface optimizations
  template:
    src: network-optimization.sh.j2
    dest: /etc/network/if-up.d/optimize-interface
    mode: '0755'
  tags: [network]

- name: Configure IRQ affinity for network interfaces
  template:
    src: irq-affinity.sh.j2
    dest: /usr/local/bin/irq-affinity.sh
    mode: '0755'
  tags: [irq, network]

- name: Create systemd service for IRQ affinity
  template:
    src: irq-affinity.service.j2
    dest: /etc/systemd/system/irq-affinity.service
    mode: '0644'
  notify: 
    - reload systemd
    - enable irq affinity
  tags: [irq, systemd]

- name: Configure memory compaction
  lineinfile:
    path: /etc/sysctl.d/99-memory-compaction.conf
    line: "{{ item }}"
    create: yes
    mode: '0644'
  loop:
    - "vm.compaction_proactiveness = 20"
    - "vm.compact_unevictable_allowed = 1"
  notify: apply sysctl
  tags: [memory]

- name: Configure NUMA balancing off for virtualization host
  sysctl:
    name: kernel.numa_balancing
    value: "0"
    state: present
    reload: yes
  tags: [numa]

- name: Configure maximum map count for containers
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes
  tags: [memory, containers]

- name: Disable additional CPU vulnerability mitigations for performance
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "kernel.unprivileged_bpf_disabled", value: "0" }
  ignore_errors: yes
  tags: [cpu, security, performance]

- name: Optimize connection tracking for high-traffic BitTorrent
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "net.netfilter.nf_conntrack_max", value: "1048576" }
    - { key: "net.netfilter.nf_conntrack_tcp_timeout_established", value: "300" }
    - { key: "net.netfilter.nf_conntrack_tcp_timeout_time_wait", value: "10" }
    - { key: "net.netfilter.nf_conntrack_tcp_timeout_close_wait", value: "10" }
    - { key: "net.netfilter.nf_conntrack_buckets", value: "262144" }
    - { key: "net.netfilter.nf_conntrack_tcp_timeout_fin_wait", value: "30" }
    - { key: "net.netfilter.nf_conntrack_tcp_timeout_last_ack", value: "30" }
  ignore_errors: yes  # Netfilter modules may not be loaded
  tags: [network, conntrack, bittorrent]